apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service-config
  namespace: telemedicine
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres-service:5432/telemedicine
        username: telemedicine_user
        password: telemedicine_password
      jpa:
        properties:
          hibernate:
            '[default_schema]': appointment
        hibernate:
          ddl-auto: update
        show-sql: false
      kafka:
        bootstrap-servers: kafka-service:29092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
          group-id: appointment-service-group
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    server:
      port: 8080

    logging:
      level:
        org.springframework.boot: INFO
        org.springframework.web: INFO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: telemedicine
  labels:
    app: appointment-service
    tier: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
        tier: service
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: appointment-service
          image: telemedicine/appointment-service:latest
          imagePullPolicy: Never # For local development
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'kubernetes'
          resources:
            requests:
              memory: '512Mi'
              cpu: '200m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: appointment-service-config
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            [
              'sh',
              '-c',
              'until pg_isready -h postgres-service -p 5432 -U telemedicine_user; do echo waiting for database; sleep 2; done;',
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: telemedicine
  labels:
    app: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
      name: http
  type: NodePort
