apiVersion: v1
kind: ConfigMap
metadata:
  name: session-service-config
  namespace: telemedicine
data:
  application.properties: |
    # MongoDB Configuration
    spring.data.mongodb.host=mongodb-service
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=telemedicine_sessions

    # Kafka Configuration
    spring.kafka.bootstrap-servers=kafka-service:29092
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.consumer.group-id=session-service-group
    spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
    spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

    # Application Configuration
    server.port=8080

    # Logging Configuration
    logging.level.org.springframework.boot=INFO
    logging.level.org.springframework.web=INFO

    # Logging Configuration
    logging.level.org.springframework.boot.actuator=DEBUG
    logging.level.org.springframework.web=DEBUG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: telemedicine
  labels:
    app: session-service
    tier: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
        tier: service
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: session-service
          image: telemedicine/session-service:latest
          imagePullPolicy: Never # For local development
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'kubernetes'
          resources:
            requests:
              memory: '512Mi'
              cpu: '200m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: session-service-config
      initContainers:
        - name: wait-for-mongodb
          image: mongo:7-jammy
          command:
            [
              'sh',
              '-c',
              'until mongo --host mongodb-service:27017 --eval "db.adminCommand(\"ping\")"; do echo waiting for mongodb; sleep 2; done;',
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: telemedicine
  labels:
    app: session-service
spec:
  selector:
    app: session-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
      name: http
  type: NodePort
